[package]
name = "regex-stack-size"
version = "0.1.0"
edition = "2021"

[features]
default = ["regex"]
regex = []
lite = []


[dependencies]
rlimit = "0.10.1"
regex = { version = "1.10.2", default-features = false, features = ["perf", "unicode"] }
regex-lite = "0.1.5"